### ISSUE TITLE
Cache images

### ISSUE THREAD

**Issue by Naramsim** [andreferreiradlw/pokestats#31]
> This is just a suggestion.

This project caught my eyes, it's very neat and provides a lot of info. I was thinking that maybe you could use https://github.com/PokeAPI/pokeapi-js-wrapper and especially its feature to cache images:

https://github.com/PokeAPI/pokeapi-js-wrapper#caching-images

Just enabling the SW without actually using the wrapper would be a huge benefit for subsequent page loadings.

**Comment by andreferreiradlw** [comment]
Hi @Naramsim, thanks a lot for the suggestion. This is actually one of the things I'm looking to improve in the app and your SW will make things a lot easier!
I'll open a ticket to address this. In its current state, the app is still very raw and a lot of work still needs to be done but I'm glad you liked it :)

**Comment by Naramsim** [comment]
Yeah, I really liked it. I'm looking forward to seeing how you'll enhance it :P 

Feel free to close this issue if you will open one by yourself.
