### ISSUE TITLE
Increase Expiration of Cached Images

### ISSUE THREAD

**Issue by andreferreiradlw** [andreferreiradlw/pokestats#39]
Currently, the service worker is only caching image responses from Github for 5 minutes. Preferably, we would like to cache these for a much longer period (at least a month).

<img width="766" alt="Screenshot 2021-01-17 at 13 20 48" src="https://user-images.githubusercontent.com/43468798/104844257-1e003b80-58c7-11eb-8443-0904256fcd1d.png">

**Comment by Naramsim** [comment]
Hi @andreferreiradlw, `ServiceWorker`s and `Cache`s don't work that way.

Once you put something in a cache it's your job to delete/update it. There is no such mechanism that reads the headers of your cached responses and revalidates them. In fact, right now Pokemon images downloaded by Pokestats are cached forever.

Check out this article to find out more: https://developers.google.com/web/ilt/pwa/caching-files-with-service-worker

And here a super cool example: https://phyks.me/2019/01/manage-expiration-of-cached-assets-with-service-worker-caching.html

**Comment by andreferreiradlw** [comment]
@Naramsim right, this makes a lot more sense. For some reason I was thinking that the cache expiration was controlled by the `cache-control` header in the response, this is set by the server and the client side has no easy way control them (for security purposes). 

I'll mark this issue as resolved now, thanks for the clarification and the great resources!
