### ISSUE TITLE
Remove "arrow up" char on the Details component

### ISSUE THREAD

**Issue by Naramsim** [andreferreiradlw/pokestats#41]
Pokeapi serves data just as it is scraped from the Nintendo Pokemon ROMs. Thus sometimes it contains some hidden strange characters which were used as a hack to separate text.

Specifically, in the details pane, you are rendering the flavor text for a specific Pokemon. These almost always contain that char. Browsers render it as an arrow pointing up.

![meganium](https://user-images.githubusercontent.com/8996268/104961917-a241e400-59d7-11eb-8c27-4e40e68377a7.PNG)

You can use this code to get rid of this annoyance:

```js
        # Page breaks are treated just like newlines.
        # Soft hyphens followed by newlines vanish.
        # Letter-hyphen-newline becomes letter-hyphen, to preserve real
        # hyphenation.
        # Any other newline becomes a space.
        html = flavor_text.replace(u'\f',       u'\n') \
                          .replace(u'\u00ad\n', u'') \
                          .replace(u'\u00ad',   u'') \
                          .replace(u' -\n',     u' - ') \
                          .replace(u'-\n',      u'-') \
                          .replace(u'\n',       u' ')
```

Reference:

https://github.com/veekun/pokedex/issues/321
https://github.com/veekun/pokedex/issues/218

**Comment by andreferreiradlw** [comment]
@Naramsim I was wondering where these characters were coming from, weirdly enough I can only see them on the `production` build and not on `dev`. Thanks for the help!

I'll implement your solution soon 👍🏻
